### ISSUE TITLE
Sedežni redi učilnic

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/izpit#10]
Slišal sem, da nekateri sedežni redi niso čisto pravilni. Prav tako verjetno manjkajo nekatere učilnice z Jadranske 19. Prilagam [PDF z vsemi sedežnimi redi](https://github.com/matijapretnar/izpit/files/1421118/ucilnice.pdf) in prosim zainteresirano javnost, da pove, kaj je v redu in kaj je treba popraviti. Spodaj je seznam vseh že urejenih učilnic.

- [x] P.01
- [x] P.02
- [x] P.04
- [x] P.05
- [x] 2.01
- [x] 2.02
- [x] 2.03
- [x] 2.04
- [x] 2.05
- [x] 3.04
- [x] 3.05
- [x] 3.06
- [x] 3.07
- [x] 3.10
- [x] 3.11
- [x] 3.12
- [x] F1
- [x] F2
- [x] MFP
- [x] VFP

**Comment by jaanos** [comment]
Lahko potrdim, da so sedežni redi za 3.05, 3.10, 3.11 in 3.12 zagotovo pravilni.

**Comment by jaanos** [comment]
Sem se malo sprehodil okoli in ugotovil sledeče:
* v P.01 manjka zadnja miza v koloni s katedrom,
* v P.04 in P.05 manjka nekaj stolov, tako da so ponekod po trije stoli v skupini namesto štirih (v P.05 sta manjkajoča stola zadaj, v P.04 pa treh manjkajočih stolov nisem videl drugje),
* v F1 je dodana miza za 2 pred prvo vrsto,
* v F2 je kateder premaknjen na sredino,
* ostale predavalnice na Jadranski 21 imajo pravilen sedežni red (edino 3.04 nisem uspel preveriti, ampak verjamem, da tam ni sprememb).

VFP in MFP nisem preverjal, prav tako ne prostorov, ki jih še nimamo.

Bom odprl pull request s spremembami v P.01, F1 in F2 - manjkajoči stoli v P.04 in P.05 se mi ne zdijo nekaj, zaradi česar bi morali spreminjati razpored.

**Comment by matijapretnar** [comment]
Dragi @jaanos, to je odlično, najlepša hvala za ves trud! Po mojem se MFP in VFP nista spremenila, ker so stoli pritrjeni, ampak bom vseeno ob priliki pregledal.

**Comment by jaanos** [comment]
Sem pokukal še v 3.04, tako da lahko potrdim, da je sedežni red pravi.

**Comment by jaanos** [comment]
Za 3.12 sem odprl pull request #13, tako da se lahko nazaj obkljuka, ko bo prirdužen.

**Comment by jureslak** [comment]
`VFP` in `MFP` sta ok.

**Comment by matijapretnar** [comment]
Super, hvala!
