### ISSUE TITLE
Namesto latexiraj.bat bi lahko imeli latexiraj.py

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/izpit#8]
Tako bi bila zadeva neodvisna od operacijskega sistema. Recimo:

    import subprocess
    import glob

    datoteke = glob.glob("*.tex")
    for dat in datoteke:
        print("Delamo na {0}.".format(dat))
        subprocess.call(["pdflatex", dat])

**Comment by matijapretnar** [comment]
To spada na https://github.com/matijapretnar/generiranje-nalog/

**Comment by andrejbauer** [comment]
Sorry.
