### ISSUE TITLE
Izginjajoče prazne vrstice

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/izpit#9]
V datoteki `latexiraj.bat`, kot jo zgenerira zdaj, manjka prazna vrstica med `cd naloge` in `pdflatex XXX.tex`. Kludge je, da se naredi takole:

    %============================================================================%
    latexiraj.bat
    %----------------------------------------------------------------------------%
    REM Kljub temu, da boste v osnovi ustvarjali datoteke v LaTeXu, lahko
    REM ustvarjate tudi druge datoteke, na primer to skripto, ki pod Windowsi
    REM požene LaTeX na vseh ustvarjenih .tex datotekah.

    REM Komentarji se v tem primeru ne začnejo z %, temveč z REM

    REM Najprej prevedemo datoteko z rešitvami ter pobrišemo pomožne datoteke.
    pdflatex resitve.tex
    del *.log *.aux

    REM Nato gremo v direktorij z nalogami in postopek ponovimo še za naloge.
    cd naloge
    REM HEJ 
    %----------------------------------------------------------------------------%
    REM Matija daj to popravi ze enkrat
    pdflatex <* ImeDatoteke[student] *>.tex
    %----------------------------------------------------------------------------%
    del *.log *.aux
    %============================================================================%

Bi pa bilo dobro to zares popraviti v `generiraj.m`. Na prvi poglej je Mathematica kriva, da odreže preveč praznih vrstic. Jih bi bilo dobro dodatni nazaj notri.

**Comment by matijapretnar** [comment]
To spada na https://github.com/matijapretnar/generiranje-nalog/
